// eslint-disable-next-line import/no-extraneous-dependencies
import { createServer, Model } from 'miragejs';

export default createServer({
  models: {
    product: Model,
  },

  seeds(server) {
    server.db.loadData({
      products: [
        {
          id: 'efb01f59-6f4a-4266-a4e6-f53b2849d9d2',
          name: 'Sicilian Pizza',
          category: 'pizza',
          popular: true,
          ingredients: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
          rating: 4,
          price: 2490,
          thumb: '/images/product/sicilian-pizza.png',
        },
        {
          id: '9401ee12-311a-4144-bb1e-557e4e4eb275',
          name: 'Speedy Pizza',
          category: 'pizza',
          popular: true,
          ingredients: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
          rating: 5,
          price: 2590,
          thumb: '/images/product/speedy-pizza.png',
        },
        {
          id: '5e233ca9-401e-4c89-be27-c10e3a965868',
          name: 'Eatalian Pizza',
          category: 'pizza',
          popular: true,
          ingredients: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
          rating: 5,
          price: 2890,
          thumb: '/images/product/eatalian-pizza.png',
        },
        {
          id: '4a73c1d9-1c7b-4e3a-affd-9dd8f5e79c30',
          name: 'Squisita Pizza',
          category: 'pizza',
          popular: true,
          ingredients: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
          rating: 5,
          price: 2890,
          thumb: '/images/product/squisita-pizza.png',
        },
        {
          id: '8e8113d6-6ab9-482e-bf49-61b8ec4d72dc',
          name: "L' Appetitosa Pizza",
          category: 'pizza',
          popular: false,
          ingredients: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
          rating: 5,
          price: 3290,
          thumb: '/images/product/l-appetitosa-pizza.png',
        },
        {
          id: '02f03751-9a84-48c4-985b-62d50a774458',
          name: 'Peperoni Pizza',
          category: 'pizza',
          popular: false,
          ingredients: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
          rating: 4,
          price: 3090,
          thumb: '/images/product/peperoni-pizza.png',
        },
        {
          id: 'c3255879-d882-41ae-924f-b97d8b00e75f',
          name: 'Cheese Burger',
          category: 'sandwich',
          popular: true,
          ingredients: 'Beef with cheese',
          rating: 4,
          price: 2690,
          thumb: '/images/product/cheese-burger.png',
        },
        {
          id: '41a7dc1d-bf5a-4d2a-a718-c3bacef40135',
          name: 'Chicken Burger',
          category: 'sandwich',
          popular: true,
          ingredients: 'Chicken with cheese',
          rating: 5,
          price: 2790,
          thumb: '/images/product/chicken-burger.png',
        },
        {
          id: '72443ee6-b42f-4798-a692-36e5bf80c65c',
          name: 'Burger Sandwich',
          category: 'sandwich',
          popular: false,
          ingredients: 'Beef with cheese',
          rating: 3,
          price: 2290,
          thumb: '/images/product/burger-sandwich.png',
        },
        {
          id: '9764ed49-6801-4dc0-b7c6-92183f8c2ceb',
          name: 'Beef Burger',
          category: 'sandwich',
          popular: false,
          ingredients: 'Beef with cheese',
          rating: 5,
          price: 2990,
          thumb: '/images/product/beef-burger.png',
        },
        {
          id: '41f20eaf-c7c0-4c5f-bb41-7fc05929fb54',
          name: 'Ice Cream Chocolate',
          category: 'ice-cream',
          popular: true,
          ingredients: 'Chocolate',
          rating: 5,
          price: 1690,
          thumb: '/images/product/ice-cream-chocolate.png',
        },
        {
          id: '871f843b-0047-47c6-a10a-d20d6e30ad35',
          name: 'Ice Cream Vanilla',
          category: 'ice-cream',
          popular: true,
          ingredients: 'Vanilla',
          rating: 5,
          price: 1690,
          thumb: '/images/product/ice-cream-vanilla.png',
        },
        {
          id: 'fca2b48f-c25b-4f85-9494-390686959538',
          name: 'Ice Cream Strawberry',
          category: 'ice-cream',
          popular: true,
          ingredients: 'Strawberry',
          rating: 5,
          price: 1690,
          thumb: '/images/product/ice-cream-strawberry.png',
        },
        {
          id: '317a7c5e-866e-4a98-a5ba-55b0eda04d37',
          name: 'Pepsi',
          category: 'drink',
          popular: true,
          ingredients: '',
          rating: 5,
          price: 1250,
          thumb: '/images/product/pepsi.png',
        },
        {
          id: '24effafd-657d-40a5-b52c-ed3e90a0adfb',
          name: 'Pepsi Diet',
          category: 'drink',
          popular: false,
          ingredients: '',
          rating: 4,
          price: 1300,
          thumb: '/images/product/pepsi-diet.png',
        },
        {
          id: 'ba5fff43-a612-4dad-9c18-02186d09baed',
          name: 'Pepsi no sugar',
          category: 'drink',
          popular: true,
          ingredients: '',
          rating: 4,
          price: 1290,
          thumb: '/images/product/pepsi-no-sugar.png',
        },
        {
          id: 'a1c9f0fe-b97e-47aa-9445-bac0945a8fe6',
          name: 'Coca Cola no sugar',
          category: 'drink',
          popular: true,
          ingredients: '',
          rating: 5,
          price: 1290,
          thumb: '/images/product/coca-cola-no-sugar.png',
        },
        {
          id: 'ecfae164-6058-4d07-8ea9-b97b01ead03b',
          name: 'Coca Cola Vanilla',
          category: 'drink',
          popular: true,
          ingredients: '',
          rating: 4,
          price: 1290,
          thumb: '/images/product/coca-cola-vanilla.png',
        },
      ],
    });
  },

  routes() {
    this.namespace = 'api';

    this.get('/products-popular', () => {
      return this.db.products.where({ popular: true });
    });

    this.get('/products', () => {
      return this.db.products;
    });
  },
});
